version: '3.9'
volumes:
  postgres_data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=lasjdvolajsdofjaolsjmdvlajmdvklajmsfv
    ports:
      - 15672:15672
      - 5672:5672

  botsdb:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: databoi
      POSTGRES_DB: bespokebots
      POSTGRES_HOST: botsdb
      DATABASE_URL: postgresql+psycopg2://postgres:databoi@botsdb:5432/bespokebots

  app:
    build: .
    #image: bespokebots_poc_app:latest
    command: waitress-serve --call --port=3000 'app:create_app' 
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    ports:
      - 3000:3000
      - 5678:5678
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=3000
      - FLASK_ENV=development
      - ENABLE_VSCODE_DEBUGGER=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BESPOKE_BOTS_SLACK_BOT_TOKEN=${BESPOKE_BOTS_SLACK_BOT_TOKEN}
      - BESPOKE_BOTS_SLACK_SIGNING_SECRET=${BESPOKE_BOTS_SLACK_SIGNING_SECRET}
      - BESPOKE_BOTS_SLACK_CLIENT_ID=${BESPOKE_BOTS_SLACK_CLIENT_ID}
      - BESPOKE_BOTS_SLACK_CLIENT_SECRET=${BESPOKE_BOTS_SLACK_CLIENT_SECRET}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - TODOIST_API_KEY=${TODOIST_API_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - PROJECT_ID=${PROJECT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=https://oauth2.googleapis.com/token
      - AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URIS=${REDIRECT_URIS}
      - DATABASE_URL=postgresql+psycopg2://postgres:databoi@botsdb:5432/bespokebots
      - USER_CREDENTIALS_KEY=${USER_CREDENTIALS_KEY}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=databoi
      - POSTGRES_DB=bespokebots
      - POSTGRES_HOST=botsdb
      - POSTGRES_PORT=5432
      - PYTHONPATH=/app

  worker:
    build: .
    #image: bespokebots_poc_worker:latest
    volumes:
      - .:/app
    command: celery -A bespokebots.services.celery_tasks worker --loglevel=info --concurrency=1 --max-memory-per-child=256000
    depends_on:
      - rabbitmq
    ports:
      - 5679:5679
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=development
      - ENABLE_VSCODE_DEBUGGER=true
      - BESPOKE_BOTS_SLACK_BOT_TOKEN=${BESPOKE_BOTS_SLACK_BOT_TOKEN}
      - BESPOKE_BOTS_SLACK_SIGNING_SECRET=${BESPOKE_BOTS_SLACK_SIGNING_SECRET}
      - BESPOKE_BOTS_SLACK_CLIENT_ID=${BESPOKE_BOTS_SLACK_CLIENT_ID}
      - BESPOKE_BOTS_SLACK_CLIENT_SECRET=${BESPOKE_BOTS_SLACK_CLIENT_SECRET}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - TODOIST_API_KEY=${TODOIST_API_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - PROJECT_ID=${PROJECT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=https://oauth2.googleapis.com/token
      - AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URIS=${REDIRECT_URIS}
      - USER_CREDENTIALS_KEY=${USER_CREDENTIALS_KEY}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=databoi
      - POSTGRES_DB=bespokebots
      - POSTGRES_HOST=botsdb
      - PYTHONPATH=/app

