version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  app:
    image: registry.digitalocean.com/bespoke-bots-poc/bespoke-bots-image:v0.0.1
    command: waitress-serve --call --port=3000 'app:create_app' 
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    ports:
      - 3000:3000
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BESPOKE_BOTS_SLACK_BOT_TOKEN=${BESPOKE_BOTS_SLACK_BOT_TOKEN}
      - BESPOKE_BOTS_SLACK_SIGNING_SECRET=${BESPOKE_BOTS_SLACK_SIGNING_SECRET}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - TODOIST_API_KEY=${TODOIST_API_KEY}

  worker:
    image: registry.digitalocean.com/bespoke-bots-poc/bespoke-bots-image:v0.0.1
    volumes:
      - .:/app
    command: celery -A bespokebots.services.celery_tasks worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BESPOKE_BOTS_SLACK_BOT_TOKEN=${BESPOKE_BOTS_SLACK_BOT_TOKEN}
      - BESPOKE_BOTS_SLACK_SIGNING_SECRET=${BESPOKE_BOTS_SLACK_SIGNING_SECRET}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - TODOIST_API_KEY=${TODOIST_API_KEY}

