"""Remove state column from UserCredentials, add new OAuthStateToken model

Revision ID: 0fd4f18b62e2
Revises: 1797af1367e5
Create Date: 2023-08-08 13:55:38.158567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd4f18b62e2'
down_revision = '1797af1367e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_state_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', name='unique_value')
    )
    op.add_column('user_credentials', sa.Column('service_workspace_name', sa.String(), nullable=True))
    op.add_column('user_credentials', sa.Column('oauth_state_token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_credentials', 'oauth_state_tokens', ['oauth_state_token_id'], ['id'])
    op.drop_column('user_credentials', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('state', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_credentials', type_='foreignkey')
    op.drop_column('user_credentials', 'oauth_state_token_id')
    op.drop_column('user_credentials', 'service_workspace_name')
    op.drop_table('oauth_state_tokens')
    # ### end Alembic commands ###
