"""Initial database setup

Revision ID: 1797af1367e5
Revises: 
Create Date: 2023-07-25 17:38:16.919340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1797af1367e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=120), nullable=True),
    sa.Column('auth_user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('credentials', sa.LargeBinary(), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('service_user_id', sa.String(), nullable=False),
    sa.Column('service_workspace_id', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credentials')
    op.drop_table('user')
    # ### end Alembic commands ###
